### ISSUE TITLE
Why not PRAGMA user_version?

### ISSUE THREAD

**Issue by MBulli** [FilledStacks/sqflite_migration#11]
The readme says that pragma user_version is not feasible to track the database version because it is inconsistent.

Can you please elaborate why?
Sorry if that is common knowledge but intuitively I would assume that storing the db version in the db is more robust than storing it somewhere else.

**Comment by FilledStacks** [comment]
I would use it if it worked. But it doesn't. 

I tried it already, we use to use it but it's not reliable since I last tested it a year ago.

**Comment by MBulli** [comment]
Alright, thanks.
