### ISSUE TITLE
Support for bool, list and map

### ISSUE THREAD

**Issue by codedaddy-llp** [FilledStacks/sqflite_migration#5]
I need to save a data model which contains Boolean, List, Map and List<Map> is there any provision to save this type of data in database? 

If not, are planning todo?

**Comment by FilledStacks** [comment]
I don't think SQL supports those types. This is not a database, it's just a migration service that uses a normal SQLite db. You should ask on the sqflite package. But SQL doesn't support it so I doubt anyone implementing the SQL standard will add that on their own.

**Comment by codedaddy-llp** [comment]
Got you, I forgot that SQLite doesn't support list and boolean.
